#!/bin/bash
# Batch enrichment script for search queries

API_URL="https://feedops-pipeline-623866089882.us-east1.run.app/search-insights/enrich"

# First batch of 100 keywords
curl -X POST "$API_URL" \
  -H "Content-Type: application/json" \
  -d '{
    "keywords": [
      "under cabinet paper towel holder",
      "white paper towel holder",
      "brass towel stand",
      "brass soap holder",
      "recessed toilet paper holder chrome",
      "inset toilet paper holder",
      "paper towel holder",
      "toilet paper holder",
      "unlacquered brass toilet paper holder",
      "valet rods for closets",
      "glass shelf with towel bar",
      "gold paper towel holder",
      "unlacquered brass paper towel holder",
      "retractable valet rod",
      "brass toilet paper holder",
      "polished nickel shower curtain rod",
      "ceiling hung mirror",
      "polished nickel toilet paper holder",
      "copper towel bar",
      "bathroom shelf with towel bar",
      "hand towel stand",
      "wall mount paper towel holder",
      "towel ring",
      "shower door handles",
      "copper paper towel holder",
      "wall mounted soap dish",
      "in wall toilet paper holder",
      "brass coat rack",
      "bathroom shelves",
      "brass towel ring",
      "36 towel bar",
      "hotel towel rack",
      "paper towel holder wall mount",
      "focus hearts 2 hearts mirror",
      "antique brass towel bar",
      "pull out closet rod",
      "shower door knobs",
      "brass valet rod",
      "toilet paper stand",
      "chrome paper towel holder",
      "polished nickel shower rod",
      "pull out valet rod",
      "valet hook",
      "antique brass toothbrush holder",
      "wall mounted magnifying mirror",
      "shower squeegee",
      "bronze paper towel holder",
      "tie rack",
      "polished brass towel bar",
      "blue paper towel holder",
      "glass shower door towel bar",
      "polished brass toilet paper holder",
      "wall mounted makeup mirror",
      "recessed toilet paper holder brass",
      "36 inch towel bar",
      "ceiling mount mirror",
      "shower curtain rod",
      "valet rod",
      "paper towel holder countertop",
      "adjustable height floor standing makeup mirror",
      "oil rubbed bronze paper towel holder",
      "polished nickel towel rack",
      "valet rod for closet",
      "red paper towel holder",
      "recessed toilet paper holder",
      "free standing hand towel holder",
      "polished nickel shower door handle",
      "brass toothbrush holder",
      "retractable wall hook",
      "double towel bar",
      "wall mounted soap dispenser",
      "copper toilet paper holder",
      "retractable closet rod",
      "freestanding towel ring",
      "countertop paper towel holder",
      "matte black recessed toilet paper holder",
      "curved shower curtain rod",
      "paper towel holders",
      "recessed brass toilet paper holder",
      "shower door handle",
      "shelf with towel bar",
      "toilet paper holder with glass shelf",
      "antique copper towel bar",
      "wall mount soap dispenser",
      "recessed toilet paper holder brushed nickel",
      "garment rod",
      "valet hooks",
      "pewter paper towel holder",
      "black paper towel holder",
      "polished nickel toothbrush holder",
      "polished nickel shower caddy",
      "unlacquered brass appliance pull",
      "countertop hand towel holder",
      "retractable valet hook",
      "white towel bar"
    ],
    "batch_size": 100,
    "force_refresh": false
  }'

echo ""
echo "Batch 1 of 8 complete. Waiting 60 seconds for rate limiting..."
sleep 60
