import { createClient } from '@/lib/supabase/server'

interface AgentPipelineContent {
  masterSku: string
  platform: 'google' | 'bing' | 'shopify'
  title: string
  description: string
  qualityScore: number
}

/**
 * Insert content from agent pipeline in correct format.
 * Creates separate rows for title and description with all required metadata.
 *
 * CRITICAL: This function ensures content is stored in the proper schema format
 * that the dashboard expects (separate rows with content_type field).
 *
 * @param content - Content generated by the 6-agent pipeline
 * @returns Promise with success status
 *
 * @example
 * ```typescript
 * await insertAgentPipelineContent({
 *   masterSku: '1016',
 *   platform: 'google',
 *   title: '{FINISH_NAME} Towel Ring...',
 *   description: 'This towel ring features...',
 *   qualityScore: 87.2,
 * })
 * ```
 */
export async function insertAgentPipelineContent(
  content: AgentPipelineContent
) {
  const supabase = await createClient()

  // Get baseline content from product_catalog
  const { data: productData, error: productError } = await supabase
    .from('product_catalog')
    .select('title, narrative_copy')
    .eq('master_sku', content.masterSku)
    .limit(1)
    .single()

  if (productError) {
    console.warn(`Could not fetch baseline content for SKU ${content.masterSku}:`, productError)
  }

  const baselineTitle = productData?.title || null
  const baselineDescription = productData?.narrative_copy || null

  // Insert title row
  const { error: titleError } = await supabase
    .from('generated_content')
    .insert({
      master_sku: content.masterSku,
      platform: content.platform,
      content_type: 'title',
      baseline_content: baselineTitle,
      candidate_content: content.title,
      quality_score: content.qualityScore,
      generation_model: '6-agent-pipeline-gpt-4',
      generation_timestamp: new Date().toISOString(),
      is_current: true,
      version: 1,
    })

  if (titleError) {
    throw new Error(`Failed to insert title for ${content.masterSku}: ${titleError.message}`)
  }

  // Insert description row
  const { error: descError } = await supabase
    .from('generated_content')
    .insert({
      master_sku: content.masterSku,
      platform: content.platform,
      content_type: 'description',
      baseline_content: baselineDescription,
      candidate_content: content.description,
      quality_score: content.qualityScore,
      generation_model: '6-agent-pipeline-gpt-4',
      generation_timestamp: new Date().toISOString(),
      is_current: true,
      version: 1,
    })

  if (descError) {
    throw new Error(`Failed to insert description for ${content.masterSku}: ${descError.message}`)
  }

  return { success: true }
}

/**
 * Batch insert multiple SKUs from agent pipeline.
 *
 * @param contentItems - Array of content items to insert
 * @returns Promise with results array
 */
export async function batchInsertAgentPipelineContent(
  contentItems: AgentPipelineContent[]
) {
  const results = await Promise.allSettled(
    contentItems.map(item => insertAgentPipelineContent(item))
  )

  const successful = results.filter(r => r.status === 'fulfilled').length
  const failed = results.filter(r => r.status === 'rejected').length

  return {
    total: contentItems.length,
    successful,
    failed,
    results,
  }
}
